In [2]:
import numpy as np
import pandas as pd

data = {
    "Name": ["Ram", "Shyam", "Ram", "Sita", None,"Shyam","Shyam","Shyam","Ram"],
    "Age": [25, np.nan, 25, 30, 22,13,17,18,19],
    "City": ["Mumbai", "mumbai", "Mumbai", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi"]
}
print(data)
df = pd.DataFrame(data)
df

{'Name': ['Ram', 'Shyam', 'Ram', 'Sita', None, 'Shyam', 'Shyam', 'Shyam', 'Ram'], 'Age': [25, nan, 25, 30, 22, 13, 17, 18, 19], 'City': ['Mumbai', 'mumbai', 'Mumbai', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi']}

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [3]:
# First few rows
print(df.head())

# Data info
df.info()

# Summary statistics
df.describe()

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      float64
 2   City    9 non-null      object
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes

            Age
count   8.00000
mean   21.12500
std     5.43632
min    13.00000
25%    17.75000
50%    20.50000
75%    25.00000
max    30.00000

In [4]:


df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])


df

    Name     Age    City
0    Ram  25.000  Mumbai
1  Shyam  21.125  mumbai
2    Ram  25.000  Mumbai
3   Sita  30.000   Delhi
4  Shyam  22.000   Delhi
5  Shyam  13.000   Delhi
6  Shyam  17.000   Delhi
7  Shyam  18.000   Delhi
8    Ram  19.000   Delhi

In [5]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, np.nan, 25, 30,20],
    "Salary": [20000, 25000, np.nan, 40000,20000],
    "City": ["Nashik", "Delhi", "Pune", "Akola","Mumbai"]
})

df

    Age   Salary    City
0  20.0  20000.0  Nashik
1   NaN  25000.0   Delhi
2  25.0      NaN    Pune
3  30.0  40000.0   Akola
4  20.0  20000.0  Mumbai

In [6]:
# Fill multiple columns with mean

df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())

df

     Age   Salary    City
0  20.00  20000.0  Nashik
1  23.75  25000.0   Delhi
2  25.00  26250.0    Pune
3  30.00  40000.0   Akola
4  20.00  20000.0  Mumbai

In [7]:
# Increase values by 10%

df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)

df

      Age   Salary    City
0  22.000  22000.0  Nashik
1  26.125  27500.0   Delhi
2  27.500  28875.0    Pune
3  33.000  44000.0   Akola
4  22.000  22000.0  Mumbai

In [8]:
# Replace specific values

df[["City"]] = df[["City"]].replace("Mumbai", "Pune")

df

      Age   Salary    City
0  22.000  22000.0  Nashik
1  26.125  27500.0   Delhi
2  27.500  28875.0    Pune
3  33.000  44000.0   Akola
4  22.000  22000.0    Pune

In [9]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()
#FEMALE female Female FeMale
df2

      Age   Salary    City
0  22.000  22000.0  NASHIK
1  26.125  27500.0   DELHI
2  27.500  28875.0    PUNE
3  33.000  44000.0   AKOLA
4  22.000  22000.0    PUNE

In [10]:
df2.dropna()
df2["Age"] = df2["Age"].astype(int)
df2

   Age   Salary    City
0   22  22000.0  NASHIK
1   26  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0   AKOLA
4   22  22000.0    PUNE

In [ ]:
from google.colab import files

uploaded = files.upload()

In [ ]:
# Check uploaded file name
file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

In [ ]:
import pandas as pd

# Load the uploaded file
df = pd.read_csv(file_name)

df.head()

In [ ]:
df.head()

df.info()

df.isnull().sum()

In [ ]:
df["date"] = df["date"].astype(str).str.strip()
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df.info()

In [ ]:
import pandas as pd

# Numerical columns
num_cols = ["rainfall", "temperature", "humidity", "wind_speed"]

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Fill categorical missing values with mode
df["weather_condition"] = df["weather_condition"].fillna(df["weather_condition"].mode()[0])

# Check missing values
print(df.isnull().sum())

In [ ]:
df["weather_condition"] = df["weather_condition"].str.lower()

df["weather_condition"].unique()

df.head()

In [ ]:
df.to_csv("cleaned_rainfall.csv", index=False)

# Download
files.download("cleaned_rainfall.csv")

In [ ]:
import pandas as pd
from google.colab import files

# Convert to Excel
df.to_excel("cleaned_rainfall.xlsx", index=False)

# Download
files.download("cleaned_rainfall.xlsx")

In [ ]:
import pandas as pd
import numpy as np

data = {
    "name": ["Amit", "Sara", "John", "Amit", None],
    "age": [20, 21, np.nan, 20, 19],
    "gender": ["Male", "female", "Male", "Male", "FEMALE"],
    "marks": [85, 90, 105, 85, -5],
    "attendance": [90, 85, 80, 90, None],
    "city": ["Mumbai", "Delhi", "mumbai", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

In [ ]:
df.info()
df.isnull().sum()
df.describe()

In [ ]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["attendance"].fillna(df["attendance"].mean(), inplace=True)
df["name"].fillna("Unknown", inplace=True)

df

In [ ]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]

df